# docotoco by @joncoded (aka @jonchius)
# dictionary of strings 
# local.py 

l = {
  "en" : {
    "tagline" : "pdf summarizer and discusser by @joncoded",
    "ask_question" : "Ask a question", 
    "bullets" : "Bullet points",
    "discussion_history" : "Discussion history",
    "could_not_clear_namespace" : "Could not clear namespace", 
    "files_uploaded" : "File(s) uploaded",
    "loaded_chunks" : "Loaded chunks to database!",
    "loading_chunks" : "Loading chunks to database...",  
    "max_tokens" : "Maximum tokens for answer",
    "model_select" : "Select LLM (advanced)",  
    "ner" : "Named entity recognition (NER)", 
    "ner_ex" : "_Show a list of names found in the document(s)?_", 
    "no_content_found" : "No content found",
    "no_content_to_summarize" : "No content to summarize", 
    "no_summary_could_be_made" : "No summary could be made",
    "pages_processed" : "Pages processed",
    "process_click_when_ready" : "click 'Process documents' when ready",
    "process_docs" : "Process documents",     
    "processing_docs" : "Processing documents...",
    "processed_file" : "Processed file", 
    "processing_file" : "Processing file...",
    "reset_everything" : "Reset everything",
    "reset_just_the_chat" : "Reset chat", 
    "sentences" : "Sentences",
    "sentiment_analysis" : "Sentiment analysis", 
    "sentiment_analysis_ex" : "_Show the vibe of the document(s)?_",    
    "settings_docs_question" : "How would you like to summarize each PDF?",    
    "settings_chat_answers" : "How would you like to configure the chat?",  
    "splitted_documents" : "Documents splitted into chunks!",  
    "splitting_documents" : "Splitting document into chunks...",
    "start_over" : "Start over", 
    "submit_message" : "Submit", 
    "summary" : "Summary", 
    "summary_generating" : "Generating summary...",
    "summary_of_documents" : "Summary of documents", 
    "thinking" : "Thinking...",
    "files_and_settings" : "Change files and settings...", 
    "upload_documents" : "Upload documents to summarize",
    "upload_instructions" : "You can upload one (or more) PDF file(s)",
    "yes": "Yes",
    "no": "No"
  },
  "fr": {      
    "tagline" : "machine de résumé et discussion des documents PDF par @joncoded",
    "ask_question" : "Veuillez poser une question (en anglais seulement pour l'instant)", 
    "bullets" : "Puces en liste",
    "discussion_history" : "Historique de la discussion",
    "could_not_clear_namespace" : "Impossible de vider l'espace de noms", 
    "files_uploaded" : "Fichier(s) téléchargé(s)",
    "loaded_chunks" : "Morceaux chargés dans la base de données !",
    "loading_chunks" : "Chargement des morceaux dans la base de données...",
    "max_tokens" : "Nombre maximum de tokens pour la réponse",
    "model_select" : "Sélectionnez LLM (avancé)",
    "ner" : "Reconnaissance des entités nommées (NER)", 
    "ner_ex" : "_Afficher une liste des noms trouvés dans le(s) document(s)?_", 
    "no_content_found" : "Aucun contenu trouvé",
    "no_content_to_summarize" : "Aucun contenu à résumer", 
    "no_summary_could_be_made" : "Aucun sommaire n'a pu être fait",
    "pages_processed" : "Pages traitées",
    "process_click_when_ready" : "cliquez sur 'Traiter les documents' lorsque vous êtes prêt",
    "process_docs" : "Traiter les documents",     
    "processing_docs" : "Traitement des documents...",
    "processed_file" : "Fichier traité", 
    "processing_file" : "Traitement du fichier...",
    "reset_everything" : "Tout réinitialiser",
    "reset_just_the_chat" : "Réinitialiser le chat", 
    "sentences" : "Nombre de phrases",
    "sentiment_analysis" : "Analyse de sentiment", 
    "sentiment_analysis_ex" : "_Afficher l'ambiance du (des) document(s) ?_",    
    "settings_docs_question" : "Comment souhaitez-vous résumer chaque PDF ?",    
    "settings_chat_answers" : "Comment souhaitez-vous configurer le chat ?",  
    "splitted_documents" : "Documents divisés en morceaux",  
    "splitting_documents" : "Division des documents en morceaux...",
    "start_over" : "Recommencer", 
    "submit_message" : "Soumettre", 
    "summary" : "Résumé", 
    "summary_generating" : "Génération du résumé...",
    "summary_of_documents" : "Résumé des documents", 
    "thinking" : "Réflexion...",
    "files_and_settings" : "Changer les fichiers et les paramètres...", 
    "upload_documents" : "Télécharger des documents",
    "upload_instructions" : "Téléchargez un (ou plusieurs) fichier PDF à résumer (limite : 5Mo chacun)",
    "yes": "Oui",
    "no": "Non"
  },
}